name: App Bridge CI

on:
    pull_request:
        paths:
            - packages/app-bridge/**

# Ensures that only one workflow per branch will run at a time.
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    NODE_VERSION: 18
    CI: true

jobs:
    app-bridge-ci:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - name: Checkout default branch
              uses: actions/checkout@v4
              with:
                  # Disabling shallow clone is recommended for improving relevancy of reporting
                  fetch-depth: 0

            - name: Use pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: latest

            - name: Use Node.js ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "pnpm"

            - name: Install npm dependencies
              run: pnpm i --frozen-lockfile

            - name: Typecheck code
              run: pnpm --stream --filter {packages/app-bridge} typecheck

            - name: Lint code
              run: pnpm --stream --filter {packages/app-bridge} lint

            - name: Test code
              run: pnpm --stream --filter {packages/app-bridge} test:coverage

            - name: SonarCloud Scan
              uses: sonarsource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              with:
                  projectBaseDir: ./packages/app-bridge

    guideline-blocks-settings-ci:
        name: Guideline Blocks Settings CI (for checking compatibility with app-bridge)
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - name: Checkout default branch
              uses: actions/checkout@v4
              with:
                  # Disabling shallow clone is recommended for improving relevancy of reporting
                  fetch-depth: 0

            - name: Use pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: latest

            - name: Use Node.js ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "pnpm"

            - name: Install npm dependencies
              run: pnpm i --frozen-lockfile

            - name: Build local deps
              run: pnpm build:app-bridge && pnpm build:sidebar-settings

            - name: Add app-bridge dependency
              run: pnpm add @frontify/app-bridge@workspace:^ --filter {packages/guideline-blocks-settings}

            - name: Typecheck code
              run: pnpm --stream --filter {packages/guideline-blocks-settings} typecheck

            - name: Lint code
              run: pnpm --stream --filter {packages/guideline-blocks-settings} lint

            - name: Unit Test code
              run: pnpm --stream --filter {packages/guideline-blocks-settings} test

            - name: Component Tests
              run: pnpm test:components
