name: CLI CI

on:
    pull_request:
        paths:
            - packages/cli/**

# Ensures that only one workflow per branch will run at a time.
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    cli-ci:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - name: Checkout default branch
              uses: actions/checkout@v4
              with:
                  # Disabling shallow clone is recommended for improving relevancy of reporting
                  fetch-depth: 0

            - name: Use pnpm
              uses: pnpm/action-setup@v3
              with:
                  run_install: false

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: ".nvmrc"
                  cache: "pnpm"

            - name: Install npm dependencies
              run: pnpm i --frozen-lockfile

            - name: Typecheck code
              run: pnpm --stream --filter {packages/cli} typecheck

            - name: Lint code
              run: pnpm --stream --filter {packages/cli} lint

            - name: Test code
              run: pnpm --stream --filter {packages/cli} test:coverage

            - name: SonarCloud Scan
              uses: sonarsource/sonarqube-scan-action@v6
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              with:
                  projectBaseDir: ./packages/cli
