name: CLI CI

on:
    push:
        branches:
            - main
        paths:
            - packages/cli/**

env:
    NODE_VERSION: 18
    CI: true

jobs:
    cli-ci:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout default branch
              uses: actions/checkout@v3
              with:
                  # Disabling shallow clone is recommended for improving relevancy of reporting
                  fetch-depth: 0

            - name: Use pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: latest

            - name: Use Node.js ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "pnpm"

            - name: Install npm dependencies
              run: pnpm i --frozen-lockfile

            - name: Go to CLI repo
              run: cd packages/cli

            - name: Typecheck code
              run: pnpm typecheck

            - name: Lint and fix code
              run: pnpm lint

            - name: Test code
              run: pnpm test:coverage

            - name: SonarCloud Scan
              uses: sonarsource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              with:
                  projectBaseDir: ./packages/cli
