name: Continuous Integration

on:
    push:
        branches:
            - main

jobs:
    cypress-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout default branch
              uses: actions/checkout@v2

            - name: Use Node.js ${{ secrets.NODE_VERSION }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ secrets.NODE_VERSION }}

            - name: Cache dependencies
              id: npm_cache
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: node${{ secrets.NODE_VERSION }}-${{ hashFiles('package-lock.json') }}

            - name: Install dependencies
              run: npm ci

            - name: Lint and fix code
              run: npm run lint

            - name: Format code
              run: npm run format

            - name: Test code
              run: npm test
