name: Continuous Integration

on: push

env:
    NODE_VERSION: 16

jobs:
    continuous-integration:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout default branch
              uses: actions/checkout@v3

            - name: Use pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: latest

            - name: Use Node.js ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: 'pnpm'

            - name: Install npm dependencies
              run: pnpm i --frozen-lockfile

            - name: Lint and fix code
              run: pnpm lint

            - name: Test code
              run: pnpm test
