name: Semantic Pull Request Title

on:
    pull_request:
        types:
            - opened
            - edited
            - reopened
            - synchronize

jobs:
    semantic-pr-title:
        runs-on: ubuntu-latest
        steps:
            - uses: amannn/action-semantic-pull-request@v5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
