name: Typing packages CI

on:
    pull_request:
        paths:
            - packages/guideline-blocks/**
            - packages/sidebar-settings/**

# Ensures that only one workflow per branch will run at a time.
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    NODE_VERSION: 18
    CI: true

jobs:
    typing-packages-ci:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - name: Checkout default branch
              uses: actions/checkout@v3
              with:
                  # Disabling shallow clone is recommended for improving relevancy of reporting
                  fetch-depth: 0

            - name: Use pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: latest

            - name: Use Node.js ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "pnpm"

            - name: Install npm dependencies
              run: pnpm i --frozen-lockfile

            - name: Build app-bridge
              run: pnpm build:app-bridge

            - name: Lint code
              run: pnpm --stream --filter {packages/guideline-blocks} --filter {packages/sidebar-settings} lint

            - name: Build packages (+ typechecking)
              run: pnpm build:sidebar-settings && pnpm build:guideline-packages
